databases:
  - name: nexus_db
    databaseName: nexus
    user: nexus_user

services:
  - type: web
    name: nexus-backend
    env: python
    buildCommand: uv sync --frozen && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: nexus_db
          property: connectionString
      - key: REDIS_URL
        sync: false # Upstash
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: onrender.com

  - type: worker
    name: nexus-worker
    env: python
    buildCommand: uv sync --frozen
    startCommand: celery -A config worker -l info
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: nexus_db
          property: connectionString
      - key: REDIS_URL
        sync: false
